# Generated by Django 5.1.6 on 2026-02-12 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcard_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.flashcardset')),
            ],
            options={
                'db_table': 'flashcards',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetProgress',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_cards_studied', models.IntegerField(default=0)),
                ('mastered_cards', models.IntegerField(default=0)),
                ('learning_cards', models.IntegerField(default=0)),
                ('new_cards', models.IntegerField(default=0)),
                ('total_study_time_seconds', models.IntegerField(default=0)),
                ('last_studied', models.DateTimeField(blank=True, null=True)),
                ('study_streak_days', models.IntegerField(default=0)),
                ('overall_accuracy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='flashcards.flashcardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'set_progress',
                'ordering': ['-last_studied'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_cards', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='flashcards.flashcardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('times_seen', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=0)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('last_response', models.CharField(blank=True, choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to=settings.AUTH_USER_MODEL)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='flashcards.flashcard')),
                ('study_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to='flashcards.studysession')),
            ],
            options={
                'db_table': 'card_progress',
                'ordering': ['-last_reviewed'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcard_categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'updated_at'], name='flashcard_c_user_id_5b7f9f_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['user', 'updated_at'], name='flashcard_s_user_id_cb1a50_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['user', 'is_deleted'], name='flashcard_s_user_id_161c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set', 'updated_at'], name='flashcards_flashca_3133cf_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set', 'is_deleted'], name='flashcards_flashca_458623_idx'),
        ),
        migrations.AddIndex(
            model_name='setprogress',
            index=models.Index(fields=['user', 'updated_at'], name='set_progres_user_id_608930_idx'),
        ),
        migrations.AddIndex(
            model_name='setprogress',
            index=models.Index(fields=['user', 'flashcard_set', 'updated_at'], name='set_progres_user_id_ea6393_idx'),
        ),
        migrations.AddIndex(
            model_name='setprogress',
            index=models.Index(fields=['user', 'last_studied'], name='set_progres_user_id_0e6266_idx'),
        ),
        migrations.AddIndex(
            model_name='setprogress',
            index=models.Index(fields=['user', 'is_deleted'], name='set_progres_user_id_67917b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='setprogress',
            unique_together={('user', 'flashcard_set')},
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'updated_at'], name='study_sessi_user_id_b78fee_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'flashcard_set', 'started_at'], name='study_sessi_user_id_02ae77_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'is_deleted'], name='study_sessi_user_id_bd5db6_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprogress',
            index=models.Index(fields=['user', 'updated_at'], name='card_progre_user_id_64352e_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprogress',
            index=models.Index(fields=['user', 'flashcard', 'updated_at'], name='card_progre_user_id_e6ecda_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprogress',
            index=models.Index(fields=['user', 'next_review'], name='card_progre_user_id_81c9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprogress',
            index=models.Index(fields=['user', 'is_deleted'], name='card_progre_user_id_7b0d0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardprogress',
            unique_together={('user', 'flashcard')},
        ),
    ]
