# Generated by Django 5.1.6 on 2026-02-13 04:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcardset_flashcard_setprogress_studysession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('share_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('share_type', models.CharField(choices=[('public', 'Public Link'), ('private', 'Private Link')], default='public', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_copy', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='flashcards.flashcardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedSetAccess',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('copied_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_sets', to=settings.AUTH_USER_MODEL)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='flashcards.sharelink')),
            ],
            options={
                'db_table': 'shared_set_accesses',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='BluetoothShare',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('session_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paired', 'Paired'), ('transferring', 'Transferring'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluetooth_shares', to='flashcards.flashcardset')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bluetooth_receives', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluetooth_sends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bluetooth_shares',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['session_code', 'status'], name='bluetooth_s_session_bc4d3e_idx'), models.Index(fields=['sender', 'initiated_at'], name='bluetooth_s_sender__0f1ab4_idx'), models.Index(fields=['expires_at', 'status'], name='bluetooth_s_expires_1389f8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['share_code', 'is_active'], name='share_links_share_c_ad157c_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['user', 'created_at'], name='share_links_user_id_32f788_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedsetaccess',
            index=models.Index(fields=['share_link', 'viewed_at'], name='shared_set__share_l_b5fbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedsetaccess',
            index=models.Index(fields=['recipient_user', 'viewed_at'], name='shared_set__recipie_95df86_idx'),
        ),
    ]
