# Generated by Django 5.1.6 on 2026-02-15 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_sharelink_sharedsetaccess_bluetoothshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='generated_from_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FileGenerationJob',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cards_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_job', to='flashcards.flashcardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_generation_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='file_genera_user_id_432fb4_idx'), models.Index(fields=['user', 'created_at'], name='file_genera_user_id_ca08c7_idx')],
            },
        ),
    ]
