# Generated by Django 5.1.6 on 2026-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcardset_generated_from_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='last_studied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='learning_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='mastered_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='new_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='overall_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='study_streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='total_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='total_study_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
