# Generated by Django 5.1.6 on 2026-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_flashcardset_last_studied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprogress',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
