# Generated by Django 5.1.6 on 2026-02-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_cardprogress_repetitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('quiz', 'Quiz'), ('study', 'Study')], default='study', max_length=10),
        ),
    ]
