# Generated by Django 5.1.6 on 2026-02-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_studysession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='quiz_accuracy',
            field=models.FloatField(default=0.0, help_text='Percentage accuracy for quiz session (0-100)'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='quiz_score',
            field=models.IntegerField(default=0, help_text='Number of correct answers in quiz session'),
        ),
    ]
